---
# format and mount additional volume

- name: Create a ext4 filesystem
  filesystem:
    fstype: ext4
    dev: "{{ item.device }}"
  with_items: "{{ additional_volumes }}"

- name: Mount up device
  mount:
    path: "{{ item.mountPath }}"
    src: "{{ item.device }}"
    opts: defaults
    fstype: ext4
    state: mounted
  with_items: "{{ additional_volumes }}"
