---
# format and mount additional volume

- name: Create a ext4 filesystem
  filesystem:
    fstype: "{{ item.fstype | default('ext4') }}"
    dev: "{{ item.device }}"
    force: no
  with_items: "{{ additional_volumes }}"
  when: item.fstype != "cifs"

- name: Mount up device
  mount:
    path: "{{ item.mountPath }}"
    src: "{{ item.device }}"
    opts: "{{ item.mount_opts | default('defaults') }}"
    fstype: "{{ item.fstype | default('ext4') }}"
    state: mounted
  with_items: "{{ additional_volumes }}"
