---
# format and mount additional volume

- name: Create a ext4 filesystem
  filesystem:
    fstype: ext4
    dev: "{{ additional_volume_device }}"

- name: Mount up device
  mount:
    path: /mnt/{{ hostname }}-volume
    src: "{{ additional_volume_device }}"
    opts: defaults
    fstype: ext4
    state: mounted