---
# install mattermost 

- name: Ensure mattermost group exists
  group:
    name: "{{ mattermost_default_group_name }}"
    gid: "{{ mattermost_default_group_id }}"
    state: present

- name: Ensure mattermost user exists
  user:
    name: "{{ mattermost_default_user_name }}"
    uid: "{{ mattermost_default_user_id }}"
    state: present
    group: "{{ mattermost_default_group_name }}"
    append: true
    create_home: false

- name: Add management users to mattermost group
  user:
    name: "{{ item.name }}"
    groups:
    - "{{ mattermost_default_group_name }}"
    append: true
  with_items: "{{ users }}"

- name: Create install directory
  file:
    path: "{{ mattermost_install_dir }}"
    state: directory
    mode: '0770'
    owner: "{{ mattermost_default_user_name }}"
    group: "{{ mattermost_default_group_name }}"

- name: Create config directories
  file:
    path: "/mnt/{{ hostname }}-volume/mattermost/app/{{item}}"
    state: directory
    mode: '0770'
    owner: "{{ mattermost_default_user_name }}"
    group: "{{ mattermost_default_group_name }}"
  with_items:
    - data
    - logs
    - config
    - plugins
    - client-plugins

- name: Create postgres directories
  file:
    path: "/mnt/{{ hostname }}-volume/mattermost/db/var/lib/postgresql/data"
    state: directory
    mode: '0770'
    owner: "{{ mattermost_default_user_name }}"
    group: "{{ mattermost_default_group_name }}"

- name: Copy app env file
  template:
    src: app.env.j2
    dest: "{{ mattermost_install_dir }}/app.env"
    mode: '660' # rw- rw- ---
    owner: "{{ mattermost_default_user_name }}"
    group: "{{ mattermost_default_group_name }}"
  notify: Restart docker-compose

- name: Copy db env file
  template:
    src: db.env.j2
    dest: "{{ mattermost_install_dir }}/db.env"
    mode: '660' # rw- rw- ---
    owner: "{{ mattermost_default_user_name }}"
    group: "{{ mattermost_default_group_name }}"
  notify: Restart docker-compose

- name: Copy wal-g env file
  template:
    src: wal-g.env.j2
    dest: "{{ mattermost_install_dir }}/wal-g.env"
    mode: '660' # rw- rw- ---
    owner: "{{ mattermost_default_user_name }}"
    group: "{{ mattermost_default_group_name }}"
  notify: Restart docker-compose

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ mattermost_install_dir }}/docker-compose.yaml"
    mode: '660' # rw- rw- ---
    owner: "{{ mattermost_default_user_name }}"
    group: "{{ mattermost_default_group_name }}"
  notify: Restart docker-compose

- name: Start docker-compose
  docker_compose:
    project_src: "{{ mattermost_install_dir }}"
    state: present

- name: Get docker-compose path
  command: which docker-compose 
  register: docker_compose_path
  changed_when: false

- name: Ensure postgres full backup scripts is run by cron
  cron:
    name: "mattermost postgres full backup"
    minute: "0"
    hour: "3"
    # redirecting stdout/stderr both before and after -- allows to catch errors
    # in docker-compose command itself and erros in its execution
    job: >
      cd {{ mattermost_install_dir }} &&
      {{ docker_compose_path.stdout }} exec -T
      -e PGUSER="{{ mattermost_postgres_user }}"
      -e PGDATABASE="{{ mattermost_postgres_db }}"
      2>&1 > /tmp/mattermost-postgres-backup-cron
      --
      db /wal-g/full-backup.sh 2>&1 > /tmp/mattermost-postgres-backup-cron
    state: present