---
# install docker

- name: Install required packages
  become: true
  apt:
    force_apt_get: true
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    # those are used for the docker_compose ansible module
    - python3-pip
    - virtualenv
    - python3-setuptools
    state: present
    update_cache: true
    cache_valid_time: 600

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Get architecture
  shell: dpkg --print-architecture
  register: arch

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: true

- name: Install Docker
  become: true
  apt:
    force_apt_get: true
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update_cache: true

- name: Add docker group
  become: true
  group:
    name: docker
    state: present

- name: Adding users to the docker group
  become: true
  user:
    name: "{{ item.name }}"
    groups: docker
    append: true
  with_items: "{{ users }}"

- name: Enable and start docker
  become: true
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Module for Python
  become: true
  pip:
    name: docker

- name: Install docker-compose Module for Python
  become: true
  pip:
    name: docker-compose