---
# configure apt sources

- name: Upgrade the server with apt-get
  apt:
    force_apt_get: yes
    update_cache: yes
    upgrade: safe

- name: Install unattended upgrades
  apt:
    force_apt_get: yes
    pkg: unattended-upgrades
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Adjust APT update intervals
  copy:
    src: etc/apt/apt.conf.d/10periodic
    dest: /etc/apt/apt.conf.d/10periodic
