---
- name: Update SSH config with basic security defaults
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "sshd -T -f %s"
    mode: 0644
  with_items:
  - regexp: "^Port"
    line: "Port {{ ssh_port }}"
  - regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  - regexp: "^PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  - regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  - regexp: "^X11Forwarding"
    line: "X11Forwarding no"
  notify: Restart ssh

- name: Enable and start SSH
  service:
    name: ssh
    state: started
    enabled: true
