---
# Install dotfiles

- name: Clone dotfiles
  git:
    repo: "https://github.com/tbalthazar/dotfiles"
    dest: "$HOME/.dotfiles"
  register: clone_dotfiles

- name: Install dotfiles
  command:
    cmd: "rcup -v -d $HOME/.dotfiles/dotfiles -t linux-desktop"
  when: clone_dotfiles.changed