---
# Install Go

- name: Install Go plugin for asdf
  command:
    cmd: "asdf plugin add golang"
  when: not asdf_plugin_list.stdout is search("golang")

- name: Get latest Go version available for asdf
  command:
    cmd: "asdf latest golang"
  register: asdf_latest_golang
  changed_when: false

- name: List Go versions installed by asdf
  command:
    cmd: "asdf list golang"
  register: asdf_list_golang
  changed_when: false

- name: Install latest version of Go with asdf
  command:
    cmd: "asdf install golang {{ asdf_latest_golang.stdout }}"
  when: not asdf_list_golang.stdout is search(asdf_latest_golang.stdout)
  register: asdf_install_golang

- name: Set default Go version with asdf
  command:
    cmd: "asdf global golang {{ asdf_latest_golang.stdout }}"
  when: asdf_install_golang.changed