---
# Install alacritty from Docker image

- name: Check if alacritty is already installed
  command: which alacritty
  register: alacritty_installed
  failed_when: false
  changed_when: false

- name: Download alacritty install script
  get_url:
    url: https://raw.githubusercontent.com/tbalthazar/dockerfiles/main/alacritty-builder/install.sh
    dest: /tmp/install-alacritty.sh
    mode: "0755"
  when: alacritty_installed.stdout == ""

- name: Execute the alacritty install script
  become: true
  script: /tmp/install-alacritty.sh
  when: alacritty_installed.stdout == ""

- name: Set alacritty as the default terminal
  become: true
  command: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/alacritty 50 