---
# Install fzf

- name: Clone fzf
  git:
    repo: "https://github.com/junegunn/fzf"
    dest: "$HOME/.fzf"  

- name: Install fzf
  command:
    cmd: "$HOME/.fzf/install --all"
    creates: "$HOME/.fzf.zsh"