---
# useful tools

- name: Install fzf
  include_tasks: fzf.yml
  when: "tools is defined and 'fzf' in tools"

- name: Install kubectl
  include_tasks: kubectl.yml
  when: "tools is defined and 'kubectl' in tools"

- name: Install Nextcloud Client
  include_tasks: nextcloud-client.yml
  when: "tools is defined and 'nextcloud-client' in tools"

- name: Install NordVPN
  include_tasks: nordvpn.yml
  when: "tools is defined and 'nordvpn' in tools"

- name: Install Transmission Client
  include_tasks: transmission-client.yml
  when: "tools is defined and 'transmission-client' in tools"

- name: Install VirtualBox
  include_tasks: virtualbox.yml
  when: "tools is defined and 'virtualbox' in tools"

- name: Install VirtualBox Guest Additions
  include_tasks: virtualbox-guest-additions.yml
  when: "tools is defined and 'virtualbox-guest-additions' in tools"

- name: Install VSCode
  include_tasks: vscode.yml
  when: "tools is defined and 'vscode' in tools"

# TODO:
# - kube_ps1
# - terraform
# - signal
# - chrome
# - vlc
# - alacritty
# - remove i3/.Xresources config from dotfiles if using regolith