---
# useful tools

- name: Install fzf
  include_tasks: fzf.yml
  when: "tools is defined and 'fzf' in tools"

- name: Install kubectl
  include_tasks: kubectl.yml
  when: "tools is defined and 'kubectl' in tools"

# TODO:
# - kube_ps1
# - terraform
# - vscode
# - nordvpn
# - transmission (to get v3)
# - signal
# - virtualbox
# - chrome
# - nextcloud latest