---
# useful tools

- name: Install fzf
  include_tasks: fzf.yml
  when: "tools is defined and 'fzf' in tools"

- name: Install kubectl
  include_tasks: kubectl.yml
  when: "tools is defined and 'kubectl' in tools"

- name: Install NordVPN
  include_tasks: nordvpn.yml
  when: "tools is defined and 'nordvpn' in tools"

- name: Install VirtualBox
  include_tasks: virtualbox.yml
  when: "tools is defined and 'virtualbox' in tools"

- name: Install VSCode
  include_tasks: vscode.yml
  when: "tools is defined and 'vscode' in tools"

# TODO:
# - kube_ps1
# - terraform
# - transmission (to get v3)
# - signal
# - chrome
# - nextcloud latest