---
# Install Signal

- name: Check if Signal is already installed
  command: which signal-desktop
  register: signal_installed
  failed_when: false
  changed_when: false

- name: Add GPG apt Key
  become: true
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/signal-desktop-keyring.gpg
  when: signal_installed.stdout == ""

- name: Add Repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64  signed-by=/etc/apt/trusted.gpg.d/signal-desktop-keyring.gpg]  https://updates.signal.org/desktop/apt xenial main"
    state: present
  when: signal_installed.stdout == ""

- name: Install Signal
  become: true
  apt:
    pkg:
    - "signal-desktop"
    state: present
    update_cache: true
    cache_valid_time: 600
  when: signal_installed.stdout == ""