---
# Install helm

- name: Check if helm is already installed
  command: which helm
  register: helm_installed
  failed_when: false
  changed_when: false

- name: Add GPG apt Key
  become: true
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  when: helm_installed.stdout == ""

- name: Get architecture
  shell: dpkg --print-architecture
  register: arch
  changed_when: false

- name: Add Repository
  become: true
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present
  when: helm_installed.stdout == ""

- name: Install helm
  become: true
  apt:
    pkg:
    - "helm"
    state: present
    update_cache: true
    cache_valid_time: 600