---
# install nextcloud 

- name: Create install directory
  file:
    path: "/opt/nextcloud"
    state: directory
    mode: '0700'

# - name: Create config directories
#   file:
#     path: "/mnt/{{ hostname }}-volume/mattermost/app/{{item}}"
#     state: directory
#     mode: '0700'
#     owner: "2000"
#     group: "2000"
#   with_items:
#     - data
#     - logs
#     - config
#     - plugins
#     - client-plugins

- name: Create postgres directories
  file:
    path: "/mnt/{{ hostname }}-volume/nextcloud/db/var/lib/postgresql/data"
    state: directory

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml.j2
    dest: "/opt/nextcloud/docker-compose.yaml"

- name: Start docker-compose
  docker_compose:
    project_src: "/opt/nextcloud"
    restarted: yes
  register: output