---
# install nextcloud 

- name: Create install directory
  file:
    path: "/opt/nextcloud"
    state: directory
    mode: '0700'

- name: Create postgres directories
  file:
    path: "/mnt/{{ hostname }}-volume/nextcloud/db/var/lib/postgresql/data"
    state: directory
    mode: '700' # rwx --- ---

- name: Copy app env file
  template:
    src: app.env.j2
    dest: "/opt/nextcloud/app.env"
  notify: Restart docker-compose

- name: Copy db env file
  template:
    src: db.env.j2
    dest: "/opt/nextcloud/db.env"
  notify: Restart docker-compose

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml.j2
    dest: "/opt/nextcloud/docker-compose.yaml"
  notify: Restart docker-compose

- name: Start docker-compose
  docker_compose:
    project_src: "/opt/nextcloud"
    state: present