---
# install traefik 

- name: Create install directory
  file:
    path: "/opt/traefik"
    state: directory
    mode: '0700'

- name: Create config directories
  file:
    path: "/mnt/{{ hostname }}-volume/traefik/config"
    state: directory
    mode: '711' # rwx --x --x

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml.j2
    dest: "/opt/traefik/docker-compose.yaml"
  notify: Restart docker-compose

- name: Copy traefik config
  template:
    src: traefik.yaml.j2
    dest: "/mnt/{{ hostname }}-volume/traefik/config/traefik.yaml"
  notify: Restart docker-compose

- name: Create a docker network
  docker_network:
    name: traefik-proxy
  notify: Restart docker-compose

- name: Start docker-compose
  docker_compose:
    project_src: "/opt/traefik"
    state: present
    pull: yes