---
# install jellyfin 

- name: Install apt-transport-https
  apt:
    force_apt_get: yes
    pkg: apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Add universe repo
  apt_repository:
    repo: universe
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] }} universe"
    state: present

- name: Add jellyfin GPG apt Key
  apt_key:
    url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
    state: present

- name: Add jellyfin repository
  apt_repository:
    repo: "deb [arch=amd64] https://repo.jellyfin.org/ubuntu {{ ansible_facts['distribution_release'] }} main"
    state: present

- name: Install jellyfin
  apt:
    force_apt_get: yes
    pkg: jellyfin
    state: present
    update_cache: yes

- name: Enable and start jellyfin service
  systemd:
    state: started
    enabled: yes
    name: jellyfin
      
- name: Allow web traffic traffic
  ufw:
    rule: allow
    port: 8096
    proto: tcp
