---
# install jellyfin 

- name: Install required packages
  apt:
    force_apt_get: yes
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items:
  - apt-transport-https
  - gnupg
  - intel-media-va-driver
  - intel-gpu-tools

- name: Ensure group "syslog" exists with correct gid
  group:
    name: syslog
    state: present
    gid: 120

- name: Ensure group "video" exists with correct gid
  group:
    name: video
    state: present
    gid: 44

- name: Ensure group "render" exists with correct gid
  group:
    name: render
    state: present
    gid: 103

- name: Add universe repo
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] }} universe"
    state: present

- name: Add jellyfin GPG apt Key
  apt_key:
    url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
    state: present

- name: Add jellyfin repository
  apt_repository:
    repo: "deb [arch=amd64] https://repo.jellyfin.org/ubuntu {{ ansible_facts['distribution_release'] }} main"
    state: present

- name: Install jellyfin
  apt:
    force_apt_get: yes
    pkg: jellyfin
    state: present
    update_cache: yes

- name: Add jellyfin user to appropriate groups
  user:
    name: jellyfin
    groups: video,render
    append: yes

- name: Enable and start jellyfin service
  systemd:
    state: started
    enabled: yes
    name: jellyfin
      
- name: Allow web traffic traffic
  ufw:
    rule: allow
    port: 8096
    proto: tcp
